---
title: 
---
<!-- Title: Your document should have a title that briefly summarizes your data analysis -->

<!-- Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?
    Across the United States, which types of events have the greatest economic consequences? -->

<!-- Does the analysis include description and justification for any data transformations?
    Does the analysis start from the raw data file (i.e. the original .csv.bz2 file)?
    Does the analysis address the question of which types of events are most harmful to population health?
    Does the analysis address the question of which types of events have the greatest economic consequences?
    Do all the results of the analysis (i.e. figures, tables, numerical summaries) appear to be reproducible?
    Do the figure(s) have descriptive captions (i.e. there is a description near the figure of what is happening in the figure)? -->

## Synopsis
<!-- Synopsis: Immediately after the title, there should be a synopsis which describes and summarizes your analysis in at most 10 complete sentences. -->

## Data Processing
<!-- There should be a section titled Data Processing which describes (in words and code) how the data were loaded into R and processed for analysis. 
    In particular, your analysis must start from the raw CSV file containing the data. You cannot do any preprocessing outside the document. 
    If preprocessing is time-consuming you may consider using the cache = TRUE option for certain code chunks. -->
```{r processing, cache=TRUE}
library(plotly)
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2", "stormdata.csv.bz2", "curl")
storm <- read.csv("stormdata.csv.bz2", header=TRUE, as.is=TRUE)
# EVTYPE = event type
# FATALITIES + INJURIES = exactly what they sound like
# PROPDMG + PROPDMGEXP = property damage; EXP is "K=thousand", "M=million"
# same deal for CROPDMG
# only keep relevant columns
storm <- storm[, c(8, 23:28)]
# combine fatalities and injuries into one category (casualties)
storm$CASUALTIES <- storm$FATALITIES + storm$INJURIES
# condense *DMG and *DMGEXP
for (i in 1:dim(storm)[1]) {
    if (storm$PROPDMGEXP == "K") {
        storm$PROPDMG = storm$PROPDMG * 1000;
    }
    else if (storm$PROPDMGEXP == "M") {
        storm$PROPDMG = storm$PROPDMG * 1000000;
    }
    else if (storm$PROPDMGEXP == "B") {
        storm$PROPDMG = storm$PROPDMG * 1000000000;
    }
    if (storm$CROPDMGEXP == "K") {
        storm$CROPDMG = storm$CROPDMG * 1000;
    }
    else if (storm$CROPDMGEXP == "M") {
        storm$CROPDMG = storm$CROPDMG * 1000000;
    }
    else if (storm$CROPDMGEXP == "B") {
        storm$CROPDMG = storm$CROPDMG * 1000000000;
    }
}
```
The data used in this report (found [here](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2)) comes from the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database.
It includes information about severe weather events throughout the U.S., including casualties and economic damage.

## Results
<!-- There should be a section titled Results in which your results are presented.
    You may have other sections in your analysis, but Data Processing and Results are required.
    The analysis document must have at least 1 figure containing a plot.
    Your analysis must have no more than 3 figures. Figures may have multiple plots in them (i.e. panel plots), 
    but there cannot be more than three figures total.
    You must show all your code for the work in your analysis document. This may make the document a bit verbose, but that is okay. 
    In general, you should ensure that echo = TRUE for every code chunk (this is the default setting in knitr). -->
```{r graphs}
plot_ly(x=storm$EVTYPE, y=storm$CASUALTIES, type="bar") 
    %>% add_trace(xaxis=list(title="Event Type"), yaxis=list(title="Casualties"))
plot_ly(x=storm$EVTYPE, y=storm$CROPDMG, type="bar", name="Crop Damage") 
    %>% add_trace(y=storm$PROPDMG, name="Property Damage") 
    %>% layout(xaxis=list(title="Event Type"), yaxis=list(title="Cost"), barmode="stack")
```